insert into category(id, name) values (1, 'Food');
insert into category(id, name) values (2, 'Clothes');
insert into category(id, name) values (3, 'Healthcare');
insert into category(id, name) values (4, 'Toys');

insert into product(id, name, price, category_id) values(1, 'Dog Red Sweater', 22, 2);
insert into product(id, name, price, category_id) values(2, 'Dog Black Sweater', 24, 2);
insert into product(id, name, price, category_id) values(3, 'Dog Blue Sweater', 20, 2);
insert into product(id, name, price, category_id) values(4, 'Dog Black Sweater', 21, 2);
insert into product(id, name, price, category_id) values(5, 'Dog Gold Sweater', 27, 2);
insert into product(id, name, price, category_id) values(6, 'Cat Gold Sweater', 29, 2);
insert into product(id, name, price, category_id) values(7, 'Cat Yellow Sweater', 20, 2);
insert into product(id, name, price, category_id) values(8, 'Bandana Collar', 7, 2);
insert into product(id, name, price, category_id) values(9, 'Bandana Collar', 10, 2);
insert into product(id, name, price, category_id) values(10, 'Large Breed Adult Dog Food - Chicken & Rice', 10, 1);
insert into product(id, name, price, category_id) values(11, 'Small Breed Adult Dog Food - Chicken & Rice', 10, 1);
insert into product(id, name, price, category_id) values(12, 'Medium Breed Adult Dog Food - Chicken & Rice', 10, 1);
insert into product(id, name, price, category_id) values(13, 'Cat Food - Chicken & Rice', 11, 1);
insert into product(id, name, price, category_id) values(14, 'Cat Food - Turkey & Salmon', 11, 1);
insert into product(id, name, price, category_id) values(15, 'Cat Food - Duck & Rice', 11, 1);
insert into product(id, name, price, category_id) values(16, 'Cat Food - Grain Free', 12, 1);
insert into product(id, name, price, category_id) values(17, 'Medium Breed Adult Dog Food - Turkey & Salmon', 14, 1);
insert into product(id, name, price, category_id) values(18, 'Small Breed Adult Dog Food - Turkey & Salmon', 14, 1);
insert into product(id, name, price, category_id) values(19, 'Large Breed Adult Dog Food - Turkey & Salmon', 14, 1);
insert into product(id, name, price, category_id) values(20, 'Advanced Supplement For Adult Dogs', 14, 3);
insert into product(id, name, price, category_id) values(21, 'Advanced Supplement For Adult Cats', 14, 3);
insert into product(id, name, price, category_id) values(22, 'Advanced Supplement For Senior Cats', 14, 3);
insert into product(id, name, price, category_id) values(23, 'Advanced Supplement For Senior Dogs', 14, 3);
insert into product(id, name, price, category_id) values(24, 'Advanced Supplement For Junior Dogs', 14, 3);
insert into product(id, name, price, category_id) values(25, 'Advanced Supplement For Junior Cats', 14, 3);
insert into product(id, name, price, category_id) values(26, 'Teddy Small Plush Toys for Dogs', 18, 4);
insert into product(id, name, price, category_id) values(27, 'Teddy Small Plush Toys for Cats', 18, 4);
insert into product(id, name, price, category_id) values(28, 'Small Plush Toys for Cats', 18, 4);
insert into product(id, name, price, category_id) values(29, 'Small Plush Toys for Dogs', 18, 4);
insert into product(id, name, price, category_id) values(30, 'Toyz Space Ball Dog Toy, Large', 10, 4);
insert into product(id, name, price, category_id) values(31, 'Toyz Space Ball Dog Toy, Medium', 10, 4);
insert into product(id, name, price, category_id) values(32, 'Toyz Space Ball Dog Toy, Small', 10, 4);
